//
// Created by jupiter on 11.06.18.
//

#ifndef FACTORY_THREAD_SIMULATION_PRODUCTSTOCKPILLE_H
#define FACTORY_THREAD_SIMULATION_PRODUCTSTOCKPILLE_H


class ProductStockpille {

};


#endif //FACTORY_THREAD_SIMULATION_PRODUCTSTOCKPILLE_H
